import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.util.*;
import java.util.List;
import com.google.gson.*;

/**
 * GanttChartVisualizer - Interactive visualizer for SM-CPTD schedules
 * 
 * Reads JSON files generated by GanttChartGenerator.java and creates a Gantt chart visualization with support for:
 * - VM filtering
 * - Critical Path highlighting
 * - Duplicate task highlighting
 * - Timeline zoom
 * - Image export
 * 
 * Usage:
 *   java GanttChartVisualizer <path-to-json-file>
 *   or
 *   java GanttChartVisualizer
 */

public class GanttChartVisualizer extends JFrame {
    
    
    private static class GanttData {
        Metadata metadata;
        List<VMInfo> vms;
        List<TaskInfo> tasks;
        List<ScheduleEntry> schedule;
        List<Integer> criticalPath;
        List<Duplication> duplications;
        List<Integer> overflowTasks;
    }
    
    private static class Metadata {
        String workflow;
        int numTasks;
        int numVMs;
        double ccr;
        double makespan;
        String timestamp;
        int criticalPathSize;
        int overflowTaskCount;
    }
    
    private static class VMInfo {
        int id;
        double processingCapacity;
    }
    
    private static class TaskInfo {
        int id;
        double size;
        double ast;  // Actual Start Time
        double aft;  // Actual Finish Time
        Integer vmId;
        boolean isCritical;
        boolean isDuplicated;
        boolean isOverThreshold;
        List<Integer> predecessors;
        List<Integer> successors;
    }
    
    private static class ScheduleEntry {
        int vmId;
        List<TaskExecution> tasks;
    }
    
    private static class TaskExecution {
        int taskId;
        double start;
        double end;
        double duration;
        double size;
        boolean isCritical;
        boolean isDuplicate;
        boolean isOverThreshold;
    }
    
    private static class Duplication {
        int vmId;
        List<Integer> duplicatedTaskIds;
    }
        
    private GanttData data;
    private GanttPanel ganttPanel;
    
    // Controls
    private JComboBox<String> vmFilterCombo;
    private JCheckBox showCriticalPathCheck;
    private JCheckBox showDuplicatesCheck;
    private JSlider zoomSlider;
    private JLabel statsLabel;
    
    // Colors
    private static final Color COLOR_NORMAL = new Color(59, 130, 246);      // Blue
    private static final Color COLOR_CRITICAL = new Color(239, 68, 68);     // Red
    private static final Color COLOR_DUPLICATE = new Color(251, 191, 36);   // Amber
    private static final Color COLOR_OVERFLOW = new Color(168, 85, 247);    // Purple
    private static final Color COLOR_BG = new Color(249, 250, 251);         // Light gray
    private static final Color COLOR_GRID = new Color(229, 231, 235);       // Gray
    private static final Color COLOR_TEXT = new Color(31, 41, 55);          // Dark gray
        
    public GanttChartVisualizer(String jsonFilePath) {
        super("SM-CPTD Gantt Chart Visualizer");
        
        // Require a file path
        if (jsonFilePath == null || jsonFilePath.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                "Error: No JSON file specified.\n\n" +
                "Usage: java GanttChartVisualizer <path-to-json-file>",
                "Missing File Path",
                JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        
        // Load data
        loadData(jsonFilePath);
        
        if (data == null) {
            System.exit(1);
        }
        
        // Setup UI
        initComponents();
        setupLayout();
        
        // Window settings
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1600, 900);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize window for better single-page view
        
        updateVisualization();
    }
        
    private void loadData(String filePath) {
        try {
            Gson gson = new GsonBuilder().create();
            Reader reader = new FileReader(filePath);
            data = gson.fromJson(reader, GanttData.class);
            reader.close();
            
            System.out.println("✅ Loaded: " + filePath);
            System.out.println("   Workflow: " + data.metadata.workflow);
            System.out.println("   Tasks: " + data.metadata.numTasks);
            System.out.println("   VMs: " + data.metadata.numVMs);
            System.out.println("   Makespan: " + String.format("%.2f", data.metadata.makespan));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading JSON file:\n" + e.getMessage(),
                "Load Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
        
    private void initComponents() {
        // VM Filter
        vmFilterCombo = new JComboBox<>();
        vmFilterCombo.addItem("All VMs");
        if (data != null) {
            for (VMInfo vm : data.vms) {
                vmFilterCombo.addItem("VM " + vm.id);
            }
        }
        vmFilterCombo.addActionListener(e -> updateVisualization());
        
        // Checkboxes
        showCriticalPathCheck = new JCheckBox("Show Critical Path", true);
        showCriticalPathCheck.addActionListener(e -> updateVisualization());
        
        showDuplicatesCheck = new JCheckBox("Show Duplicates", true);
        showDuplicatesCheck.addActionListener(e -> updateVisualization());
        
        // Zoom slider
        zoomSlider = new JSlider(JSlider.HORIZONTAL, 1, 50, 5);
        zoomSlider.setMajorTickSpacing(10);
        zoomSlider.setMinorTickSpacing(5);
        zoomSlider.setPaintTicks(true);
        zoomSlider.setPaintLabels(true);
        zoomSlider.addChangeListener(e -> updateVisualization());
        
        // Stats label
        statsLabel = new JLabel();
        updateStatsLabel();
        
        // Gantt panel
        ganttPanel = new GanttPanel();
    }
    
    private void setupLayout() {
        setLayout(new BorderLayout(10, 10));
        
        // Top panel with controls
        JPanel topPanel = new JPanel(new BorderLayout(10, 10));
        topPanel.setBorder(new EmptyBorder(10, 10, 10, 10));
        topPanel.setBackground(Color.WHITE);
        
        // Title and metadata
        JPanel titlePanel = new JPanel(new BorderLayout());
        titlePanel.setBackground(Color.WHITE);
        
        if (data != null) {
            JLabel titleLabel = new JLabel(
                String.format("📊 %s Workflow - %d tasks × %d VMs (CCR=%.1f)", 
                    data.metadata.workflow.toUpperCase(),
                    data.metadata.numTasks,
                    data.metadata.numVMs,
                    data.metadata.ccr));
            titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
            titlePanel.add(titleLabel, BorderLayout.NORTH);
            titlePanel.add(statsLabel, BorderLayout.SOUTH);
        }
        
        topPanel.add(titlePanel, BorderLayout.NORTH);
        
        // Controls panel
        JPanel controlsPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 5));
        controlsPanel.setBackground(Color.WHITE);
        
        controlsPanel.add(new JLabel("Filter:"));
        controlsPanel.add(vmFilterCombo);
        controlsPanel.add(Box.createHorizontalStrut(10));
        controlsPanel.add(showCriticalPathCheck);
        controlsPanel.add(showDuplicatesCheck);
        controlsPanel.add(Box.createHorizontalStrut(10));
        controlsPanel.add(new JLabel("Zoom:"));
        controlsPanel.add(zoomSlider);
        
        // Buttons
        JButton fitButton = new JButton("Fit to Page");
        fitButton.addActionListener(e -> fitToPage());
        controlsPanel.add(Box.createHorizontalStrut(10));
        controlsPanel.add(fitButton);
        
        JButton exportButton = new JButton("Export PNG");
        exportButton.addActionListener(e -> exportToPNG());
        controlsPanel.add(exportButton);
        
        topPanel.add(controlsPanel, BorderLayout.CENTER);
        
        add(topPanel, BorderLayout.NORTH);
        
        // Legend panel
        JPanel legendPanel = createLegendPanel();
        add(legendPanel, BorderLayout.SOUTH);
        
        // Center: Gantt chart with scrollpane
        JScrollPane scrollPane = new JScrollPane(ganttPanel);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getViewport().setBackground(COLOR_BG);
        add(scrollPane, BorderLayout.CENTER);
    }
    
    private JPanel createLegendPanel() {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createTitledBorder("Legend"));
        
        panel.add(createLegendItem("Normal Task", COLOR_NORMAL));
        panel.add(createLegendItem("Critical Path", COLOR_CRITICAL));
        panel.add(createLegendItem("Duplicated", COLOR_DUPLICATE));
        panel.add(createLegendItem("Over Threshold", COLOR_OVERFLOW));
        
        return panel;
    }
    
    private JPanel createLegendItem(String label, Color color) {
        JPanel item = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 0));
        item.setBackground(Color.WHITE);
        
        JPanel colorBox = new JPanel();
        colorBox.setPreferredSize(new Dimension(20, 20));
        colorBox.setBackground(color);
        colorBox.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        item.add(colorBox);
        item.add(new JLabel(label));
        
        return item;
    }
    
    private void updateStatsLabel() {
        if (data == null) return;
        
        Set<Integer> criticalPathSet = new HashSet<>(data.criticalPath);
        Set<Integer> duplicatedSet = new HashSet<>();
        for (Duplication dup : data.duplications) {
            duplicatedSet.addAll(dup.duplicatedTaskIds);
        }
        
        String stats = String.format(
            "⏱️ Makespan: %.2f | 🎯 Critical Path: %d tasks | 📋 Duplicated: %d tasks | ⚠️ Overflow: %d tasks",
            data.metadata.makespan,
            criticalPathSet.size(),
            duplicatedSet.size(),
            data.overflowTasks.size()
        );
        
        statsLabel.setText(stats);
        statsLabel.setFont(new Font("Arial", Font.PLAIN, 12));
    }
    
    
    private void updateVisualization() {
        if (ganttPanel != null) {
            ganttPanel.repaint();
        }
    }
    
    private void fitToPage() {
        if (data == null) return;
        
        // Get available width from the scroll pane
        Container parent = ganttPanel.getParent();
        if (parent instanceof JViewport) {
            JViewport viewport = (JViewport) parent;
            int availableWidth = viewport.getWidth() - GanttPanel.LEFT_MARGIN - GanttPanel.RIGHT_MARGIN - 20;
            
            // Calculate zoom to fit
            double makespan = data.metadata.makespan;
            int targetZoom = Math.max(1, Math.min(50, (int) (availableWidth / makespan)));
            
            zoomSlider.setValue(targetZoom);
        }
    }
        
    private class GanttPanel extends JPanel {
        private static final int ROW_HEIGHT = 50;
        private static final int LEFT_MARGIN = 100;
        private static final int TOP_MARGIN = 60;
        private static final int BOTTOM_MARGIN = 20;
        private static final int RIGHT_MARGIN = 30;
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            
            if (data == null) {
                g.setColor(COLOR_TEXT);
                g.setFont(new Font("Arial", Font.PLAIN, 16));
                g.drawString("No data loaded. Click 'Load JSON' to begin.", 50, 50);
                return;
            }
            
            Graphics2D g2d = (Graphics2D) g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            
            // Get filtered schedule
            List<ScheduleEntry> filtered = getFilteredSchedule();
            if (filtered.isEmpty()) {
                g2d.setColor(COLOR_TEXT);
                g2d.drawString("No data for selected filter", LEFT_MARGIN, TOP_MARGIN);
                return;
            }
            
            // Calculate dimensions
            double maxTime = data.metadata.makespan;
            double zoom = zoomSlider.getValue();
            int chartWidth = (int) (maxTime * zoom);
            int chartHeight = filtered.size() * ROW_HEIGHT;
            
            // Set panel size
            setPreferredSize(new Dimension(
                LEFT_MARGIN + chartWidth + RIGHT_MARGIN,
                TOP_MARGIN + chartHeight + BOTTOM_MARGIN
            ));
            revalidate();
            
            // Draw background
            g2d.setColor(COLOR_BG);
            g2d.fillRect(0, 0, getWidth(), getHeight());
            
            // Draw time axis
            drawTimeAxis(g2d, maxTime, zoom, chartWidth);
            
            // Draw VM rows
            drawVMRows(g2d, filtered, zoom, chartHeight);
            
            // Draw tasks
            drawTasks(g2d, filtered, zoom);
        }
        
        private List<ScheduleEntry> getFilteredSchedule() {
            String selected = (String) vmFilterCombo.getSelectedItem();
            
            if (selected.equals("All VMs")) {
                return data.schedule;
            } else {
                // Extract VM id from "VM X"
                int vmId = Integer.parseInt(selected.substring(3));
                return data.schedule.stream()
                    .filter(entry -> entry.vmId == vmId)
                    .collect(java.util.stream.Collectors.toList());
            }
        }
        
        private void drawTimeAxis(Graphics2D g2d, double maxTime, double zoom, int chartWidth) {
            g2d.setColor(COLOR_TEXT);
            g2d.setFont(new Font("Arial", Font.BOLD, 13));
            g2d.drawString("Time →", LEFT_MARGIN, TOP_MARGIN - 35);
            
            // Draw time markers - adaptive based on zoom
            g2d.setFont(new Font("Arial", Font.PLAIN, 10));
            int numMarkers = Math.min(25, Math.max(10, (int) (chartWidth / 60)));
            double step = maxTime / numMarkers;
            
            for (int i = 0; i <= numMarkers; i++) {
                double time = i * step;
                int x = LEFT_MARGIN + (int) (time * zoom);
                
                // Vertical grid line
                g2d.setColor(COLOR_GRID);
                g2d.setStroke(new BasicStroke(1));
                g2d.drawLine(x, TOP_MARGIN, x, TOP_MARGIN + getHeight());
                
                // Time label
                g2d.setColor(COLOR_TEXT);
                String label = String.format("%.1f", time);
                FontMetrics fm = g2d.getFontMetrics();
                int labelWidth = fm.stringWidth(label);
                g2d.drawString(label, x - labelWidth / 2, TOP_MARGIN - 8);
            }
            
            // Draw axis line
            g2d.setStroke(new BasicStroke(2));
            g2d.setColor(COLOR_TEXT);
            g2d.drawLine(LEFT_MARGIN, TOP_MARGIN, LEFT_MARGIN + chartWidth, TOP_MARGIN);
        }
        
        private void drawVMRows(Graphics2D g2d, List<ScheduleEntry> schedule, double zoom, int chartHeight) {
            g2d.setFont(new Font("Arial", Font.BOLD, 13));
            
            for (int i = 0; i < schedule.size(); i++) {
                ScheduleEntry entry = schedule.get(i);
                int y = TOP_MARGIN + i * ROW_HEIGHT;
                
                // Row background first
                g2d.setColor(i % 2 == 0 ? Color.WHITE : new Color(249, 250, 251));
                g2d.fillRect(LEFT_MARGIN, y, getWidth() - LEFT_MARGIN, ROW_HEIGHT);
                
                // VM label
                g2d.setColor(COLOR_TEXT);
                String vmLabel = String.format("VM %d", entry.vmId);
                g2d.drawString(vmLabel, 10, y + ROW_HEIGHT / 2 + 2);
                
                // Capacity info
                VMInfo vmInfo = data.vms.stream()
                    .filter(vm -> vm.id == entry.vmId)
                    .findFirst()
                    .orElse(null);
                
                if (vmInfo != null) {
                    g2d.setFont(new Font("Arial", Font.PLAIN, 10));
                    g2d.setColor(new Color(100, 100, 100));
                    g2d.drawString(String.format("%.0f MIPS", vmInfo.processingCapacity), 
                        10, y + ROW_HEIGHT / 2 + 15);
                    g2d.setFont(new Font("Arial", Font.BOLD, 13));
                }
                
                // Row border
                g2d.setColor(COLOR_GRID);
                g2d.setStroke(new BasicStroke(1));
                g2d.drawLine(LEFT_MARGIN, y + ROW_HEIGHT, getWidth(), y + ROW_HEIGHT);
            }
        }
        
        private void drawTasks(Graphics2D g2d, List<ScheduleEntry> schedule, double zoom) {
            Set<Integer> criticalPathSet = new HashSet<>(data.criticalPath);
            Set<Integer> duplicatedSet = new HashSet<>();
            for (Duplication dup : data.duplications) {
                duplicatedSet.addAll(dup.duplicatedTaskIds);
            }
            Set<Integer> overflowSet = new HashSet<>(data.overflowTasks);
            
            for (int i = 0; i < schedule.size(); i++) {
                ScheduleEntry entry = schedule.get(i);
                int y = TOP_MARGIN + i * ROW_HEIGHT;
                
                for (TaskExecution task : entry.tasks) {
                    // Determine color
                    Color color = COLOR_NORMAL;
                    
                    if (showCriticalPathCheck.isSelected() && 
                        (task.isCritical || criticalPathSet.contains(task.taskId))) {
                        color = COLOR_CRITICAL;
                    } else if (showDuplicatesCheck.isSelected() && 
                               (task.isDuplicate || duplicatedSet.contains(task.taskId))) {
                        color = COLOR_DUPLICATE;
                    } else if (task.isOverThreshold || overflowSet.contains(task.taskId)) {
                        color = COLOR_OVERFLOW;
                    }
                    
                    // Calculate position and size
                    int x = LEFT_MARGIN + (int) (task.start * zoom);
                    int width = Math.max(3, (int) (task.duration * zoom)); // Minimum width of 3px
                    int height = 35;
                    int taskY = y + (ROW_HEIGHT - height) / 2;
                    
                    // Draw task rectangle
                    g2d.setColor(color);
                    g2d.fillRoundRect(x, taskY, width, height, 8, 8);
                    
                    // Draw border
                    g2d.setColor(color.darker());
                    g2d.setStroke(new BasicStroke(2));
                    g2d.drawRoundRect(x, taskY, width, height, 8, 8);
                    
                    // Draw task label if wide enough
                    if (width > 25) {
                        g2d.setColor(Color.WHITE);
                        g2d.setFont(new Font("Arial", Font.BOLD, 11));
                        
                        String label = "T" + task.taskId;
                        FontMetrics fm = g2d.getFontMetrics();
                        int labelWidth = fm.stringWidth(label);
                        int labelX = x + (width - labelWidth) / 2;
                        int labelY = taskY + (height + fm.getAscent()) / 2 - 2;
                        
                        g2d.drawString(label, labelX, labelY);
                        
                        // Duration and timing labels
                        if (width > 70) {
                            g2d.setFont(new Font("Arial", Font.PLAIN, 9));
                            String durationLabel = String.format("%.1f", task.duration);
                            labelWidth = g2d.getFontMetrics().stringWidth(durationLabel);
                            labelX = x + (width - labelWidth) / 2;
                            g2d.drawString(durationLabel, labelX, taskY + height - 4);
                        }
                    } else if (width > 10) {
                        // For small tasks, just show task ID outside the bar
                        g2d.setColor(COLOR_TEXT);
                        g2d.setFont(new Font("Arial", Font.BOLD, 9));
                        g2d.drawString("T" + task.taskId, x + width + 2, taskY + height / 2 + 3);
                    }
                }
            }
        }
    }
        
    private void exportToPNG() {
        JFileChooser fileChooser = new JFileChooser("../results/figures");
        fileChooser.setSelectedFile(new File("gantt_chart.png"));
        
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            try {
                // Create image
                int width = ganttPanel.getPreferredSize().width;
                int height = ganttPanel.getPreferredSize().height;
                
                java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(
                    width, height, java.awt.image.BufferedImage.TYPE_INT_RGB);
                
                Graphics2D g2d = image.createGraphics();
                ganttPanel.paint(g2d);
                g2d.dispose();
                
                // Save to file
                javax.imageio.ImageIO.write(image, "PNG", file);
                
                JOptionPane.showMessageDialog(this,
                    "Gantt chart exported successfully to:\n" + file.getAbsolutePath(),
                    "Export Success",
                    JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error exporting image:\n" + e.getMessage(),
                    "Export Error",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }
        
    public static void main(String[] args) {
        // Check for required argument
        if (args.length == 0) {
            System.err.println("Error: No JSON file specified.");
            System.err.println();
            System.err.println("Usage: java GanttChartVisualizer <path-to-json-file>");
            System.err.println();
            System.err.println("Example:");
            System.err.println("  java GanttChartVisualizer results/gantt_charts/ligo_50_tasks_5_vms_ccr1.8_run7.json");
            System.exit(1);
        }
        
        String jsonPath = args[0];
        
        // Verify file exists
        File jsonFile = new File(jsonPath);
        if (!jsonFile.exists()) {
            System.err.println("Error: File not found: " + jsonPath);
            System.exit(1);
        }
        
        if (!jsonFile.isFile()) {
            System.err.println("Error: Not a file: " + jsonPath);
            System.exit(1);
        }
        
        // Set look and feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Launch UI
        SwingUtilities.invokeLater(() -> {
            GanttChartVisualizer visualizer = new GanttChartVisualizer(jsonPath);
            visualizer.setVisible(true);
        });
    }
}